# Intro to Python: Syntax
Part of the workshop series presented by the [IDEA Student Center at UC San Diego](http://www.jacobsschool.ucsd.edu/student/).

### Goals
Practice some common programming tasks using Python, including how to achieve the same results as Matlab in Python.

### Requirements
- numpy = for loading data and vectorized calculations
- matplotlib = for plotting

In [2]:
# make the code compatible with both Python 2 and 3
from __future__ import print_function, division

# load the numpy package (which gives us much of the same functionality as matlab)
import numpy as np

# also load matplotlib (for plotting/visualization)
import matplotlib.pyplot as plt
%matplotlib inline

/Users/david/anaconda/envs/workshops/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


## 1) Common syntax
We'll cover common programming tasks:
- for loops
- make vectors in a range

### 1.1) For loops

In [5]:
# loop through numbers
for i in range(5):
    print(i)

0
1
2
3
4


In [6]:
# print even numbers from 0 up to (but not including) 10
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


In [7]:
# print even numbers from 0 up to (and including 10)
for i in range(0, 10 + 1, 2):
    print(i)

0
2
4
6
8
10


In [12]:
# loop through items in a list

# make a list of names
names = ['David', 'Carlos', 'Rachel']

# print each name in the list
for name in names:
    print(name)

David
Carlos
Rachel


In [10]:
# make a list of names
names = ['David', 'Carlos', 'Rachel']

# print each name in the list
for name in names:
    print("My name is", name)

My name is David
My name is Carlos
My name is Rachel


In [11]:
# make a list of numbers
angles = [1, 2, 3, 4, 5]

# use the elements of the list in calculations
for angle in angles:
    print( angle * 10 )

10
20
30
40
50


### 1.2) Formatting strings

In [16]:
# pick a name
name = 'Jennifer'

print("My name is", name)

# alternative syntax 1
#print("My name is " + name)

# alternative syntax 2
#print("My name is {0}".format(name))

My name is Jennifer


In [22]:
# formatting numbers
T = 273.05840957484 # temperature [K]
P = 1.01            # pressure [atm]

# display temperature and pressure using Python defaults
print( "Temperature [K] =", T)
print( "Pressure [atm] =", P)

# display the temperature as a floating point number, with
# 3 decimal places of precision
print( "Temperature [K] = {0:.3f}".format(T) )

# display the pressure as a floating point number, with
# 2 decimal places of precision
print( "Pressure [K] = {0:.2f}".format(P) )

Temperature [K] = 273.058409575
Pressure [atm] = 1.01
Temperature [K] = 273.058
Pressure [K] = 1.01


In [25]:
# display text and numbers together

filename = "experiment_01.csv"
voltage = 3.30
error = 0.58470548

print( "{0}: {1:.2f} [V], error = {2:.3f}".format(filename, voltage, error) )

experiment_01.csv: 3.30 [V], error = 0.585


In [26]:
print( "{0}: {1:.2f} [V], error = {2:.3f}".format("experiment_01.csv", 3.3, 0.58470548) )
print( "{0}: {1:.2f} [V], error = {2:.3f}".format("experiment_02.csv", 3.6, 0.65960505) )
print( "{0}: {1:.2f} [V], error = {2:.3f}".format("experiment_03.csv", 3.9, 0.69896580) )
print( "{0}: {1:.2f} [V], error = {2:.3f}".format("experiment_04.csv", 4.2, 0.73438940) )

experiment_01.csv: 3.30 [V], error = 0.585
experiment_02.csv: 3.60 [V], error = 0.660
experiment_03.csv: 3.90 [V], error = 0.699
experiment_04.csv: 4.20 [V], error = 0.734


### 1.3) Creating lists of numbers

In [27]:
# vector of ones, with length 10
x = np.ones(10)
print( x )

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [30]:
# 5 x 5 array of zeroes
A = np.zeros([5, 5])
print( A )

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [33]:
# 3 x 3 identity matrix
A = np.eye(3)
print( A )

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [35]:
# create a list of numbers, with a specified minimum, maximum and step size
x = np.arange(0, 5, 1)   # from 0, up to 5, in steps of 1
print( x )

[0 1 2 3 4]


In [40]:
# create a list of numbers of a specific length
x = np.linspace(0, 1, 10)  # from 0 to 1, with 10 elements total
print( x )

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]
